import './globals.css'
import { Inter } from 'next/font/google'
import './styles.css'
import Link from 'next/link'
import Nickname from './component/Nickname'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <header>
          <nav className='menu-container'>
            <div>
              {<Nickname/>}
            </div>
            <Link href="http://localhost:8080/oauth2/authorization/google" className='menu-button'>
              <div className='menu-button'>
                구글 로그인
              </div>
            </Link>
            <Link href="http://localhost:8080/oauth2/authorization/naver" className='menu-button'>
              <div className='menu-button'>
                네이버 로그인
              </div>
            </Link>
            <Link href="http://localhost:8080/oauth2/authorization/kakao" className='menu-button'>
              <div className='menu-button'>
                카카오 로그인
              </div>
            </Link>
          </nav>
        </header>
        
        
          {children}
      </body>
    </html>
  )
}
